import React,{useState,useEffect,useCallback,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ResponsiveContainer,LineChart,Line,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {Building2,LayoutDashboard,Table2,LifeBuoy,Database,LogOut,Download,Plus,RefreshCw,ArrowUpRight,ShieldCheck} from 'lucide-react';
import './style.css';
const reports={'rent-roll':'Rent roll',overdue:'Overdue balances',occupancy:'Occupancy trend',expiry:'Lease expiry',maintenance:'Maintenance turnaround',collection:'Payment collection'};
const entities={properties:'Properties',units:'Units',tenants:'Tenants',leases:'Leases',charges:'Rent charges',receipts:'Payment receipts',maintenance:'Maintenance',tickets:'Support tickets'};
const fields={
 properties:{name:'text',address:'text',city:'text',created_date:'date'},
 units:{property_id:'number',unit_number:'text',rent_paise:'money',available_from:'date'},
 tenants:{name:'text',email:'email',phone:'text'},
 leases:{tenant_id:'number',unit_id:'number',start_date:'date',end_date:'date',monthly_rent_paise:'money',status:['active','ended','cancelled']},
 charges:{lease_id:'number',amount_paise:'money',due_date:'date',description:'text'},
 receipts:{charge_id:'number',amount_paise:'money',paid_date:'date',reference:'text',method:['UPI','Bank transfer','Cash']},
 maintenance:{unit_id:'number',tenant_id:'number',issue:'textarea',priority:['low','medium','high','urgent'],status:['open','in_progress','resolved'],created_date:'date',resolved_date:'nullable-date'},
 tickets:{description:'textarea',related_table:['properties','units','tenants','leases','charges','receipts','maintenance'],related_id:'number',status:['open','investigating','resolved'],resolution_notes:'nullable-textarea'}
};
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0)/100);
const label=k=>k.replaceAll('_paise',' (INR)').replaceAll('_',' ').replace(/^./,x=>x.toUpperCase());
const date=()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);};
function value(k,v){if(v===null||v===undefined)return '—';if(k.endsWith('_paise'))return money(v);if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='object')return JSON.stringify(v);return String(v);}
function DataTable({rows,actions}){if(!rows.length)return <div className="empty">No matching records for this view.</div>;const keys=Object.keys(rows[0]);return <div className="table-scroll"><table><thead><tr>{keys.map(k=><th key={k}>{label(k)}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k} className={k.endsWith('_paise')?'amount':''}>{k==='status'?<span className={'badge '+r[k]}>{r[k]}</span>:value(k,r[k])}</td>)}{actions&&<td><div className="row-actions">{actions(r)}</div></td>}</tr>)}</tbody></table></div>;}
function MarketContext({market}){return <section className="panel market-context"><div className="panel-header"><div><p className="eyebrow">PUBLIC MARKET DATA</p><h2>Indian housing-price movement</h2><p className="muted">Annual HPI change for the quarter ended {market.quarter_end}.</p></div><a className="market-source" href={market.source_url} target="_blank" rel="noreferrer">National Housing Bank source<ArrowUpRight size={15}/></a></div><div className="market-grid">{market.rows.map(row=><article className={row.composite?'composite':''} key={row.city}><span>{row.city}</span><strong>{row.annual_change_pct>0?'+':''}{row.annual_change_pct}%</strong></article>)}</div><p className="muted small">These are published NHB RESIDEX statistics. Properties and all tenant, lease, payment and support records are anonymized or generated.</p></section>;}
function Login({onLogin}){const [error,setError]=useState(''),[busy,setBusy]=useState('');
 async function enter(role){setBusy(role);setError('');try{const r=await fetch('/api/auth/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Demo access is unavailable');onLogin(body);}catch(e){setError(e.message);}finally{setBusy('');}}
 return <main className="login"><section className="login-intro"><Building2 size={42}/><h1>PropertyPulse</h1><p>Every property.<br/>Every payment.<br/>A clearer picture.</p><div className="login-note">Property management & application support</div></section><section className="login-form"><p className="eyebrow">INTERACTIVE DEMO</p><h2>Choose how to explore</h2><p className="muted">Use administrator mode to test record changes and ticket resolution, or viewer mode to verify read-only access.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="role-buttons"><button className="primary" type="button" disabled={Boolean(busy)} onClick={()=>enter('admin')}>{busy==='admin'?'Opening…':'Continue as Administrator'}<ArrowUpRight size={18}/></button><button type="button" disabled={Boolean(busy)} onClick={()=>enter('viewer')}>{busy==='viewer'?'Opening…':'Continue as Viewer'}<ArrowUpRight size={18}/></button></div><p className="muted small">Includes public NHB market statistics and privacy-safe generated operations. Demo changes reset automatically.</p></section></main>;
}
function RecordForm({entity,record,submit,onClose,title}){
 const [draft,setDraft]=useState(()=>Object.fromEntries(Object.entries(fields[entity]).map(([k,type])=>[k,record?.[k]!=null?(type==='money'?String(record[k]/100):String(record[k]).slice(0,type.includes?.('date')?10:10000)):Array.isArray(type)?type[0]:type==='date'?date():''])));
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{
  const data=Object.fromEntries(Object.entries(fields[entity]).map(([k,type])=>{const v=draft[k];if(type==='money'){if(!/^\d{1,8}(\.\d{1,2})?$/.test(v))throw new Error('Enter INR with at most two decimals');const [a,b='']=v.split('.');return [k,Number(a)*100+Number(b.padEnd(2,'0'))];}return [k,type==='number'?Number(v):String(type).startsWith('nullable')&&!v?null:v];}));
  await submit(data);onClose();
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="form-title"><h2 id="form-title">{title||`${record?'Edit':'Add'} ${entities[entity]}`}</h2><p className="muted">Amounts are entered in INR. Related IDs must exist.</p><form onSubmit={save}><div className="form-grid">{Object.entries(fields[entity]).map(([k,type])=><label key={k}>{label(k)}{Array.isArray(type)?<select value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}>{type.map(v=><option key={v}>{v}</option>)}</select>:String(type).includes('textarea')?<textarea rows={3} required={!String(type).startsWith('nullable')} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>:<input type={String(type).includes('date')?'date':type==='money'?'number':type} step={type==='money'?'0.01':type==='number'?'1':undefined} min={type==='money'?'0.01':type==='number'?'1':undefined} required={!String(type).startsWith('nullable')} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>}</label>)}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-buttons"><button type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></section></div>;
}
function App(){
 const [session,setSession]=useState(null),[view,setView]=useState('Overview'),[asOf,setAsOf]=useState('2026-09-04'),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [report,setReport]=useState('rent-roll'),[entity,setEntity]=useState('properties'),[page,setPage]=useState(1),[rows,setRows]=useState([]),[total,setTotal]=useState(0),[overview,setOverview]=useState(null),[modal,setModal]=useState(null),[diagnostic,setDiagnostic]=useState(null),[ticket,setTicket]=useState(null),[notes,setNotes]=useState(''),[actionBusy,setActionBusy]=useState(false);
 const request=useCallback(async(path,options={})=>{const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.token}`,...options.headers}});if(r.status===401){setSession(null);throw new Error('Please choose a role again');}if(!r.ok){const data=await r.json().catch(()=>({}));throw new Error(data.error||'Request failed');}return r.json();},[session]);
 const refresh=()=>setRevision(n=>n+1);
 useEffect(()=>{if(!session)return;let active=true;setBusy(true);setError('');
  const run=async()=>{try{
   if(view==='Overview'){const [kpis,occupancy,collection,market]=await Promise.all([request(`/kpis?asOf=${asOf}`),request(`/reports/occupancy?asOf=${asOf}`),request(`/reports/collection?asOf=${asOf}`),request('/market-benchmarks')]);if(active)setOverview({kpis,occupancy,collection,market});}
   else if(view==='Reports'){const data=await request(`/reports/${report}?asOf=${asOf}`);if(active)setRows(data);}
   else {const data=await request(`/entities/${view==='Tickets'?'tickets':entity}?asOf=${asOf}&page=${page}&limit=25`);if(active){setRows(data.items);setTotal(data.total);}}
  }catch(e){if(active)setError(e.message);}finally{if(active)setBusy(false);}};run();return()=>{active=false};
 },[session,view,report,entity,page,asOf,revision,request]);
 if(!session)return <Login onLogin={s=>{setSession(s);setView('Overview');setOverview(null);}}/>;
 const admin=session.user.role==='admin';
 const go=v=>{setView(v);setRows([]);setPage(1);setDiagnostic(null);setTicket(null);setError('');};
 async function remove(row){if(!window.confirm(`Delete ${entities[entity]} record #${row.id}? Related records can prevent deletion; an audit record is retained.`))return;setActionBusy(true);try{await request(`/entities/${entity}/${row.id}`,{method:'DELETE'});refresh();}catch(e){setError(e.message);}finally{setActionBusy(false);}}
 async function investigate(row){setActionBusy(true);setError('');try{setDiagnostic(await request(`/tickets/${row.id}/investigate`,{method:'POST',body:'{}'}));setTicket(row);setNotes('');refresh();}catch(e){setError(e.message);}finally{setActionBusy(false);}}
 async function resolve(){setActionBusy(true);setError('');try{await request(`/tickets/${ticket.id}/resolve`,{method:'POST',body:JSON.stringify({resolution_notes:notes})});setTicket(null);setDiagnostic(null);refresh();}catch(e){setError(e.message);}finally{setActionBusy(false);}}
 async function download(format){setActionBusy(true);try{const r=await fetch(`/api/reports/${report}/export?format=${format}&asOf=${asOf}`,{headers:{Authorization:`Bearer ${session.token}`}});if(!r.ok)throw new Error('Could not export report');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`propertypulse-${report}-${asOf}.${format}`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}finally{setActionBusy(false);}}
 const palette=['#19776c','#5476cd','#cb8649','#af6391'];
 const series=overview?[...new Set(overview.occupancy.map(x=>x.property))]:[];
 const trend=overview?Object.values(overview.occupancy.reduce((a,r)=>{a[r.month]??={month:r.month};a[r.month][r.property]=r.occupancy_pct;return a},{})):[];
 return <div className="shell"><aside><div className="brand"><Building2/>PropertyPulse</div><p className="nav-label">PORTFOLIO WORKSPACE</p><nav>{[['Overview',LayoutDashboard],['Reports',Table2],['Records',Database],['Tickets',LifeBuoy]].map(([n,Icon])=><button key={n} className={view===n?'selected':''} onClick={()=>go(n)}><Icon size={19}/>{n}</button>)}</nav><div className="sidebar-footer"><ShieldCheck size={19}/><strong>{admin?'Administrator':'Read-only viewer'}</strong><small>{session.user.name}</small><button onClick={()=>setSession(null)}><LogOut size={16}/>Switch role</button></div></aside><main className="workspace"><header><span>Workspace <span className="slash">/</span> {view}</span><span className="pill">{session.user.role}</span></header><div className="page-heading"><div><p className="eyebrow">PROPERTY OPERATIONS</p><h1>{view==='Overview'?'Portfolio overview':view==='Tickets'?'Support workspace':view==='Reports'?'Portfolio reports':'Manage records'}</h1><p className="muted">{view==='Overview'?'Occupancy, collections and the issues that need attention.':view==='Tickets'?'Investigate discrepancies. Document the correction.':view==='Reports'?'Explore the numbers behind your portfolio.':'Manage your properties, agreements and rental ledger.'}</p></div><div className="toolbar"><label className="date-label">Report date<input aria-label="Report date" type="date" value={asOf} onChange={e=>e.target.value&&setAsOf(e.target.value)}/></label><button aria-label="Refresh" disabled={busy} onClick={refresh}><RefreshCw size={17}/></button></div></div>
 {error&&<div className="error" role="alert">{error}<button onClick={refresh}>Retry</button></div>}
 {busy?<div className="loading" role="status">Loading your portfolio…</div>:<>
 {view==='Overview'&&overview&&<MarketContext market={overview.market}/>}
 {view==='Overview'&&overview&&<><div className="kpis">{[['Occupied units',`${overview.kpis.occupancy_pct}%`,`${overview.kpis.occupied_units} of ${overview.kpis.total_units} units`],['Collected this month',money(overview.kpis.collected_paise),'Through selected report date'],['Open support tickets',overview.kpis.open_tickets,'Current operational status'],['Overdue charges',overview.kpis.overdue_count,'Unpaid bills past their due date']].map(([title,note,sub],i)=><article className={'kpi kpi-'+i} key={title}><span>{title}</span><strong>{note}</strong><small>{sub}</small></article>)}</div><div className="charts"><section className="panel"><h2>Occupancy over time</h2><p className="muted">Month-end snapshots; current month through selected date</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tick={{fontSize:11}}/><YAxis domain={[0,100]} unit="%"/><Tooltip/><Legend/>{series.map((s,i)=><Line key={s} dataKey={s} stroke={palette[i%4]} strokeWidth={2.5} dot={false}/>)}</LineChart></ResponsiveContainer></div></section><section className="panel"><h2>Monthly collections</h2><p className="muted">Cash received in INR, independent of bill month</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={overview.collection.map(r=>({...r,collected:r.collected_paise/100}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tick={{fontSize:11}}/><YAxis tickFormatter={n=>`${Math.round(n/1000)}k`}/><Tooltip formatter={n=>money(n*100)}/><Bar dataKey="collected" fill="#19776c" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></section></div><div className="panel explainer"><div><h2>Keep the ledger explainable</h2><p className="muted">Follow an overdue charge to its receipts, or investigate a reported data issue.</p></div><button className="primary" onClick={()=>{setReport('overdue');go('Reports')}}>Review overdue balances<ArrowUpRight size={16}/></button></div></>}
 {view==='Reports'&&<><div className="report-tabs">{Object.entries(reports).map(([k,n])=><button className={report===k?'active':''} key={k} onClick={()=>setReport(k)}>{n}</button>)}</div><section className="panel"><div className="panel-header"><div><h2>{reports[report]}</h2><p className="muted">As of {asOf} · {rows.length} records · amounts in INR</p></div><div className="toolbar"><button disabled={actionBusy} onClick={()=>download('pdf')}><Download size={16}/>PDF</button><button disabled={actionBusy} onClick={()=>download('xlsx')}><Download size={16}/>Excel</button></div></div><DataTable rows={rows}/></section></>}
 {(view==='Records'||view==='Tickets')&&<><section className="panel"><div className="panel-header">{view==='Records'?<select aria-label="Entity" value={entity} onChange={e=>{setEntity(e.target.value);setPage(1);}}>{Object.entries(entities).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select>:<div><h2>Reported issues</h2><p className="muted">{total} tickets · viewers can read; administrators investigate and resolve</p></div>}{admin&&<button className="primary" onClick={()=>setModal({entity:view==='Tickets'?'tickets':entity})}><Plus size={17}/>{view==='Tickets'?'Raise ticket':'Add record'}</button>}</div><DataTable rows={rows} actions={admin?r=>view==='Tickets'?<button disabled={actionBusy} onClick={()=>investigate(r)}>Investigate</button>:<><button onClick={()=>setModal({entity,record:r})}>Edit</button><button className="danger" disabled={actionBusy} onClick={()=>remove(r)}>Delete</button></>:null}/><div className="pagination"><span>{total} total records</span><button disabled={page<=1} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page}</span><button disabled={page*25>=total} onClick={()=>setPage(n=>n+1)}>Next</button></div></section>
 {view==='Tickets'&&diagnostic&&<section className="panel investigation"><h2>Investigation · ticket #{ticket.id}</h2><p>{ticket.description}</p><p className="muted">{diagnostic.note}</p><h3>Related record</h3><DataTable rows={diagnostic.record?[diagnostic.record]:[]}/>{!!diagnostic.financial.length&&<><h3>Diagnostic query results</h3><DataTable rows={diagnostic.financial}/></>}<h3>Change history</h3><DataTable rows={diagnostic.history}/>{ticket.status!=='resolved'&&<><label>Resolution notes<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Explain the finding and the action taken."/></label><div className="toolbar"><button disabled={actionBusy||notes.trim().length<5} className="primary" onClick={resolve}>Resolve without data change</button><button disabled={!diagnostic.record||notes.trim().length<5} onClick={()=>setModal({entity:ticket.related_table,record:diagnostic.record,correction:true})}>Correct record & resolve</button></div><p className="muted small">Correction, audit entry and ticket resolution commit together or roll back together.</p></>}</section>}
 </>}
 </>}<footer>Independent educational project · fictional portfolio · SQL Server reporting</footer></main>
 {modal&&<RecordForm {...modal} onClose={()=>setModal(null)} title={modal.correction?'Correct data and resolve ticket':undefined} submit={async data=>{if(modal.correction){await request(`/tickets/${ticket.id}/resolve`,{method:'POST',body:JSON.stringify({resolution_notes:notes,correction:data})});setDiagnostic(null);setTicket(null);}else await request(`/entities/${modal.entity}${modal.record?'/'+modal.record.id:''}`,{method:modal.record?'PATCH':'POST',body:JSON.stringify(data)});refresh();}}/>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
